hello_world/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("users/", views.UserView.as_view(), name="users"),
    path("users/<int:pk>", views.UserView.as_view(), name="user_detail"),
    path("history/", views.SearchHistoryView.as_view(), name="history_search"),
    path(
        "history/<int:user>", views.SearchHistoryView.as_view(), name="history_detail"
    ),
    path("search", views.FlightSearchView.as_view(), name="search"),
]

ticket_locator/urls.py
from django.contrib import admin
from django.urls import path, include
from .yasg import urlpatterns as swagger
from hello_world import urls, views

urlpatterns = [
    path("", views.SearchAirRoute.as_view(), name="index"),
    path("history/", views.UserSearchHistoryView.as_view(), name="history"),
    path(
        "registration/",
        views.RegistrationView.as_view(),
        name="registration"
    ),
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("api/", include(urls)),
]
urlpatterns += swagger

hello_world/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField('staff', default=False)
    is_active = models.BooleanField('active', default=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.email


class SearchHistory(models.Model):
    departure_city = models.CharField('Departure city', max_length=128)
    arrival_city = models.CharField('Arrival city', max_length=128)
    departure_date = models.DateTimeField('Departure date')
    arrival_date = models.DateTimeField('Arrival date')
    user = models.ForeignKey('User', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Search history'
        verbose_name_plural = 'Search history'

    def __str__(self):
        return f"{self.departure_city} -> {self.arrival_city}"

hello_world/models/search_history_model.py
from django.contrib import admin
from django.db import models
from ticket_locator import settings


class SearchHistory(models.Model):
    """Model search history structure- id
    - Depart City
    - Araivl City
    - depart date
    - araivl date
    - user_id(related field with User model)"""

    class Meta:
        unique_together = (("depart_city", "arrival_city", "depart_date", "arrival_date", "user_id"),)

    id = models.BigAutoField(primary_key=True)
    depart_city = models.CharField(max_length=250, null=False)
    arrival_city = models.CharField(max_length=250, null=False)
    depart_date = models.DateField(null=False)
    arrival_date = models.DateField(null=False)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user")

    def __str__(self):
        return str(self.user_id).upper()


class SearchHistoryAdmin(admin.ModelAdmin):
    fieldsets = [
        ("User", {"fields": ["user_id"]}),
        ("City", {"fields": ["depart_city", "arrival_city"]}),
        ("Date", {"fields": ["depart_date", "arrival_date"]})
    ]
    list_display = ["user_id", "depart_city", "arrival_city", "depart_date", "arrival_date"]
    list_filter = ["user_id"]
    search_fields = ["user_id"]
    ordering = ["user_id"]
    save_on_top = True

ticket_locator/hello_world/models/search_history_model.py
from django.contrib import admin
from django.db import models

from .user_model import User

class SearchHistory(models.Model):
    """Model search history structure- id
    - Depart City
    - Araivl City
    - depart date
    - araivl date
    - user_id(related field with User model)"""

    id  = models.BigAutoField(primary_key=True)
    depart_city = models.CharField(max_length= 250, null=False)
    arrival_city = models.CharField(max_length=250, null=False)
    depart_date = models.DateField(null=False)
    arrival_date = models.DateField(null=False)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")

    def __str__(self):
        return str(self.user_id).upper()


class SearchHistoryAdmin(admin.ModelAdmin):
    fieldsets = [
        ("User", {"fields": ["user_id"]}),
        ("City", {"fields": ["depart_city","arrival_city"]}),
        ("Date", {"fields": ["depart_date", "arrival_date"]})
    ]
    list_display = ["user_id", "depart_city", "arrival_city", "depart_date", "arrival_date"]
    list_filter = ["user_id"]
    search_fields = ["user_id"]
    save_on_top = True

hello_world/forms.py
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    AuthenticationForm,
)
from django import forms

from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ("email",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email",)


class SearchAirRouteForm(forms.Form):
    ##################### Widgets ############################
    departure_airport_widget = forms.TextInput(
        attrs={
            "placeholder": "Откуда:",
            "required": True,
            "class": "form-control mt-4",
            "type": "text",
            "pattern": "[A-Z]{3}",
            "title": 'IATA код аэропорта. Пример: "BCN", "AMS" ...',
        }
    )
    arrival_airport_widget = forms.DateInput(
        attrs={
            "placeholder": "Куда:",
            "required": True,
            "class": "form-control mt-4",
            "type": "text",
            "pattern": "[A-Z]{3}",
            "title": 'IATA код аэропорта. Пример: "BCN", "AMS" ...',
        }
    )
    departure_date_widget = forms.DateInput(
        attrs={"required": True, "class": "form-control mt-4", "type": "date"}
    )
    ######################### Form ###############################
    departure_airport = forms.CharField(max_length=3, widget=departure_airport_widget)
    arrival_airport = forms.CharField(max_length=3, widget=arrival_airport_widget)
    departure_date = forms.DateField(widget=departure_date_widget)
    direct_flight = forms.BooleanField(required=False)

    def clean_departure_date(self):
        data = self.cleaned_data["departure_date"]
        prepared_date = data.strftime("%Y-%m-%d")
        return prepared_date


class RegistrationForm(UserCreationForm):
    email = forms.CharField(widget=forms.TextInput())
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = (
            "email",
            "password1",
            "password2",
        )


class LoginForm(AuthenticationForm):
    email = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("email", "password")

ticket_locator/hello_world/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import TicketLocatorUser


class TicketLocatorUserCreationForm(UserCreationForm):
    class Meta:
        model = TicketLocatorUser
        fields = ('username', 'email', 'password1', 'password2')


class TicketLocatorUserChangeForm(UserChangeForm):
    class Meta:
        model = TicketLocatorUser
        fields = ('username', 'email', 'password1', 'password2')

hello_world/views.py
from django.contrib.auth import logout, authenticate, login
from django.utils.datastructures import MultiValueDictKeyError
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.views import View
from rest_framework import status
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response

from ticket_locator.services.constants import logos
from .forms import SearchAirRouteForm, RegistrationForm, LoginForm
from .models import User, SearchHistory
from .serializers import (
    UsersListSerializer,
    UserDetailSerializer,
    SearchHistorySerializer,
    FlightSearchSerializer,
)

from celery import group
from hello_world.tasks import get_air_data
from ticket_locator.services.singaporeair_service import SingaporeAirService
from ticket_locator.services.transavia_service import TransaviaService
from ticket_locator.services.turkishairlines_service import TurkishAirlinesService

AIRLINES = ("TurkishAirlinesService", "TransaviaService", "SingaporeAirService")


class UserView(GenericAPIView):
    serializer_class = UsersListSerializer

    def get(self, request, pk=None):
        users = self.get_queryset(pk)
        serializer = (
            UsersListSerializer(users, many=True)
            if not pk
            else UserDetailSerializer(users)
        )
        return Response(serializer.data)

    def get_queryset(self, pk=None):
        if not pk:
            return User.objects.all()
        return User.objects.get(id=pk)


class SearchHistoryView(GenericAPIView):
    serializer_class = SearchHistorySerializer

    def get(self, request, user=None):
        search_history = self.get_queryset(user)
        serializer = SearchHistorySerializer(search_history, many=True)
        return Response(serializer.data)

    def get_queryset(self, user=None):
        if not user:
            return SearchHistory.objects.all()
        return SearchHistory.objects.filter(user=user)


class FlightSearchView(GenericAPIView):
    serializer_class = FlightSearchSerializer

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.flight_info = None

    @staticmethod
    def get_air_info(request_data):
        result = []
        air_tasks = group(
            [get_air_data.s(airline, request_data) for airline in AIRLINES]
        )
        flights = air_tasks.apply_async()
        while not flights.ready():
            pass
        for flight in flights.get():
            result += flight
        return result

    def start_get_air_info(self, air_company, request_data):
        result = []
        departure_airport = request_data["departure_airport"]
        arrival_airport = request_data["arrival_airport"]
        departure_date = "".join(request_data["departure_date"].split("-"))
        direct_flight = request_data.get("direct_flight")
        airlines = {
            "TurkishAirlinesService": TurkishAirlinesService,
            "TransaviaService": TransaviaService,
            "SingaporeAirService": SingaporeAirService,
        }
        if not self.flight_info:
            self.flight_info = airlines[air_company]().get_flight_info_by_date(
                departure_airport, arrival_airport, departure_date
            )
        if direct_flight:
            for flight in self.flight_info:
                if len(flight) < 2:
                    result += [flight]
        else:
            result += self.flight_info
        return result

    def post(self, request):
        try:
            if (
                request.data["departure_airport"]
                and request.data["arrival_airport"]
                and request.data["departure_date"]
            ):
                result = self.get_air_info(request.data)
                return Response(result)
        except MultiValueDictKeyError:
            return Response({"Error": "Please fill all fields."})


class SearchAirRoute(
    View
):  # view for which renders and processes the search form on the main page
    def get(self, request):
        form = SearchAirRouteForm()
        return render(
            request=request,
            template_name="hello_world/index.html",
            context={"result": "init", "form": form},
        )

    def post(self, request):

        request_post = {}
        for item in request.POST:
            request_post[item] = request.POST[item]
        request_post["departure_airport"] = request_post["departure_airport"].split(
            ","
        )[0][-4:-1]
        request_post["arrival_airport"] = request_post["arrival_airport"].split(",")[0][
            -4:-1
        ]
        form = SearchAirRouteForm(request_post)
        if form.is_valid():
            if request.user.is_authenticated:
                user = User.objects.filter(email=request.user)[0]
                data = form.cleaned_data
                SearchHistory.objects.get_or_create(
                    user=user,
                    departure_city=data["departure_airport"],
                    arrival_city=data["arrival_airport"],
                    departure_date=data["departure_date"],
                    arrival_date=f"2022-12-12 00:00",
                )
            request.data = form.cleaned_data
            result = FlightSearchView().post(request).data
            for flight in result:
                for flight_item in flight:
                    flight_item["AirlineLogo"] = logos.get(flight_item.get("Airline"))
            return render(
                request, "hello_world/index.html", {"result": result, "form": form}
            )
        return redirect("/")


class Logout(View):
    def get(self, request):
        logout(request)
        return redirect("/")


class RegistrationView(View):
    def get(self, request):
        form = RegistrationForm()
        context = {"result": "init", "form": form}
        return render(
            request=request,
            template_name="hello_world/registration.html",
            context=context,
        )

    @csrf_exempt
    def post(self, request):
        form = RegistrationForm(request.POST)
        if not form.is_valid():
            context = {"result": "Wrong", "form": form}
            return render(
                request=request,
                template_name="hello_world/registration.html",
                context=context,
            )
        form.save()
        return redirect("/login")


class Login(View):
    def get(self, request):
        form = LoginForm()
        context = {"result": "init", "form": form}
        return render(
            request=request, template_name="hello_world/login.html", context=context
        )

    @csrf_exempt
    def post(self, request):
        username = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
        else:
            form = LoginForm()
            context = {"result": "Wrong", "form": form}
            return render(
                request=request, template_name="hello_world/login.html", context=context
            )
        return redirect("/")


class UserSearchHistoryView(View):
    def get(self, request):
        search_form = SearchAirRouteForm()
        context = []
        if request.user.is_authenticated:
            context = SearchHistory.objects.filter(user=request.user).values()
        return render(
            request=request,
            template_name="hello_world/history.html",
            context={"history": context, "form": search_form},
        )

hello_world/templates/hello_world/base.html
<!doctype html>
{%load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Ticket Locator - {% block title %}{%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href="{% static 'css/typeahead.css' %}" rel="stylesheet">
    <style>
    html, body {
    height: 100%;
    }
    </style>
</head>
<body>
<div class="container bg-dark h-100 rounded">
    {% include 'hello_world/block_navbar.html' %}
    {% block search %}
    {%endblock%}
    <p></p>
    {%block content%}
    {%endblock%}
    <p></p>
</div>
<script type="text/javascript" src="{% static 'js/typeahead.js' %}"></script>
<script crossorigin="anonymous" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>

hello_world/templates/hello_world/block_history.html
{%if history%}
    {%for history_item in history %}
        <div class="text-center mx-auto mb-3 bg-light align-items-center rounded">
            <strong>Departure:</strong>
            &nbsp;&nbsp;&nbsp;
            <strong>{{history_item.departure_city}}</strong>
            <img src="/static/images/departure.png" height="50">
            &nbsp;&nbsp;&nbsp;
            <strong>{{history_item.departure_date}}</strong>
            &nbsp;&nbsp;&nbsp;
            <img src="/static/images/arrival.png" height="50">
            <strong>{{history_item.arrival_city}}</strong>
            &nbsp;&nbsp;&nbsp;
            <strong>:Arrival</strong>
        </div>
    {% endfor %}
    <hr class="mt-3 mb-0 bg-light"/>
{%else%}
<div class="row">
    <div class="col-sm-12">
        <label class="h3 text-light">Вы ещё ничего не искали...</label>
    </div>
</div>
{%endif%}

hello_world/templates/hello_world/block_search_form.html
<div class="container bg-dark rounded" style="margin-top:10px;">
    <form autocomplete="off" action="{% url 'index' %}" method="post">
        {% csrf_token %}
        <table border="0" width="100%">
            <tr>
                <td>
                    <div class="autocomplete" style="width:100%">
                        <input type="text" name="departure_airport" placeholder="Откуда:" required
                               class="form-control" pattern=".* \([A-Z]{3}\),.*"
                               id="id_departure_airport"
                               oninvalid="this.setCustomValidity('Выберите вариант из списка!')"
                               oninput="this.setCustomValidity('')"/>
                    </div>
                </td>
                <td>
                    <div class="autocomplete" style="width:100%">
                        <input type="text" name="arrival_airport" placeholder="Откуда:" required
                               class="form-control" pattern=".* \([A-Z]{3}\),.*"
                               id="id_arrival_airport"
                               oninvalid="this.setCustomValidity('Выберите вариант из списка!')"
                               oninput="this.setCustomValidity('')"/>
                    </div>
                </td>
                <td>
                    <input type="date" name="departure_date" required class="form-control" id="id_departure_date"
                           oninvalid="this.setCustomValidity('Выберите дату вылета!')"
                           oninput="this.setCustomValidity('')"/>
                </td>
                <td align="center">
                    <input type="submit" class="btn btn-dark" value="Поиск">
                </td>
            </tr>
        </table>
        <div class="custom-control custom-switch">
            <input type="checkbox" class="custom-control-input" name="direct_flight" id="id_direct_flight">
            <label class="custom-control-label text-light" for="id_direct_flight">Прямой рейс</label>
        </div>
    </form>
</div>
<hr class="mt-0 mb-0 bg-light"/>

hello_world/templates/hello_world/block_search_results.html
{%if result != "init"%}
    {%if result%}
        {%for flight_info in result %}
        <div class="container bg-white w-100 rounded">
            <div class="mt-3">
                {%for flight_item in flight_info %}
                    <div class="text-center mx-auto align-items-center">
                        <img src={{flight_item.AirlineLogo}} height="50">
                        &nbsp;
                        <strong>{{flight_item.Airline}}{{flight_item.FlightNumber}}</strong>
                        &nbsp;&nbsp;&nbsp;
                        <img src="/static/images/departure.png" height="50">
                        &nbsp;&nbsp;&nbsp;
                        <strong>{{flight_item.DepartureAirport}}&nbsp;&nbsp;&nbsp;{{flight_item.DepartureTime|slice:"0:10:1"}}
                            {{flight_item.DepartureTime|slice:"11:-3:"}}</strong>
                        &nbsp;&nbsp;&nbsp;
                        <img src="/static/images/arrival.png" height="50">
                        &nbsp;&nbsp;&nbsp;
                        <strong>{{flight_item.ArrivalAirport}}&nbsp;&nbsp;&nbsp;{{flight_item.ArrivalTime|slice:"0:10:1"}}
                            {{flight_item.ArrivalTime|slice:"11:-3:"}}</strong>
                        &nbsp;&nbsp;&nbsp;
                        <img src='/static/images/stop.png' height="50">
                    </div>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <hr class="mt-3 mb-0 bg-light"/>
    {%else%}
    <div class="row">
        <div class="col-sm-12">
            <label class="h3 text-light">Жаль, но мы ничего не нашли...</label>
        </div>
    </div>
    {%endif%}
{%endif%}

hello_world/templates/hello_world/history.html
{% extends 'hello_world/base.html' %}

{% block title %}
История
{%endblock%}

{% block search %}
{% include 'hello_world/block_search_form.html' %}
{%endblock%}

{%block content%}
{% include 'hello_world/block_history.html' %}
{%endblock%}

hello_world/templates/hello_world/index.html
   <!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Ticket Locator</title>
      <!-- Bootstrap CSS (Cloudflare CDN) -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
      </head>
        {% include "hello_world/menu.html"%}
        <body>
            <div class="container">
                <div class="col">
                <form action="{% url 'index' %}" method="post">
                     {% csrf_token %}
                          {{form_search}}
                    <p></p>
                    {%if form_search%}
                    <input type="submit" value="Search" class="btn btn-primary">
                    {%endif%}
                </form>
                </div>
            </div>
            <p></p>
            <div class = "container">
                {%block content%}
                {%endblock%}
            </div>
            <!-- Подключаем jQuery -->
        <script crossorigin="anonymous" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script crossorigin="anonymous" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
        <script crossorigin="anonymous" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        </body>
    </html>

hello_world/templates/hello_world/login.html
{% extends 'hello_world/base.html' %}

{% block title %}
Вход
{%endblock%}

{% block content %}
<div class="container bg-light w-25 rounded">
    <form class="form-signin" method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Вход</h1>
        <label for="id_{{form.email.name}}" class="sr-only">Ваш еmail</label>
        <input type="email" id="id_{{form.email.name}}" name="{{form.email.name}}" class="form-control"
               placeholder="Ваш еmail" required autofocus>
        <label for="{{form.password.id_for_label}}" class="sr-only">Password</label>
        <input type="password" id="{{form.password.id_for_label}}" name="{{form.password.name}}" class="form-control"
               placeholder="Пароль" required>
        <input name="login" class="btn btn-lg btn-primary btn-block" type="submit" value="Войти">
        {% if result == "Wrong" %}
        <label class="text-danger">Неверный логин или пароль!</label>
        {% endif %}
        <p class="mt-2 mb-3">&copy; 2021-...</p>
    </form>
</div>
{%endblock%}

hello_world/templates/hello_world/menu.html
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'index' %}"><strong>TICKET LOCATOR</strong></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        {%if user.is_authenticated%}
          <li class="nav-item active">
            <span class="nav-link">User {{user.email}}</span>
          </li>
    </ul>
      </div>

      <div class="collapse navbar-collapse" style="position:absolute; left:1450px;">
          <ul class="navbar-nav mr-auto">
         {%if user.is_superuser%}
            <li class="nav-item active">
            <a class="nav-link" href="{%url 'admin:index'%}">Admin panel</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'personal_aria'%}">Personal area</a>
          </li>

          {%elif not user.is_superuser%}
            <li class="nav-item active">
            <a class="nav-link" href="{% url 'personal_aria'%}">Personal area</a>
          </li>
           {%endif%}
          <li class="nav-item active">
        <a class="nav-link" href="">Your history</a>
            </li>
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'logout'%}">Log out</a>
          </li>
        {%else%}
            <li class="nav-item active">
        <a class="nav-link" href="{% url 'login'%}">login in</a>
      </li>
         <li class="nav-item active">
            <a class="nav-link" href="{% url 'singup'%}">Sing up</a>
          </li>
          </ul>
          {%endif%}
        </div>

</nav>

hello_world/templates/hello_world/personal_aria.html
{%extends "hello_world/index.html"%}

{% block title %}Change password{% endblock %}

{% block content %}
    <h4>Change password</h4>
    <p><a href="{% url 'password_change' %}">Change password</a></p>
{% endblock %}

hello_world/templates/hello_world/registration.html
{% extends 'hello_world/base.html' %}

{% block title %}
Регистрация
{%endblock%}

{% block content %}
<div class="container bg-light w-25 rounded">
    <form class="form-signin" method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Регистрация</h1>
        <label for="id_{{form.email.name}}" class="sr-only">Ваш еmail</label>
        <input type="email" id="id_{{form.email.name}}" name="{{form.email.name}}" class="form-control"
               placeholder="Ваш еmail" required autofocus>
        <label for="{{form.password1.id_for_label}}" class="sr-only">Password</label>
        <input type="password" id="{{form.password1.id_for_label}}" name="{{form.password1.name}}" class="form-control"
               placeholder="Пароль" required>
        <label for="{{form.password2.id_for_label}}" class="sr-only">Password</label>
        <input type="password" id="{{form.password2.id_for_label}}" name="{{form.password2.name}}" class="form-control"
               placeholder="Повторите пароль" required>
        <input name="create_user" class="btn btn-lg btn-primary btn-block" type="submit" value="Зарегистрировать">
        {% if result == "Wrong" %}
        <label class="text-danger">Что-то пошло не так!</label>
        <label class="text-danger">Проверьте введённый email.</label>
        <label class="text-danger">Ваш пароль не может быть таким-же как email.</label>
        <label class="text-danger">Ваш пароль должен содердать больше 8 символов.</label>
        <label class="text-danger">Ваш пароль не может быть только из цифр.</label>
        {% endif %}
        <p class="mt-2 mb-3">&copy; 2021-...</p>
    </form>
</div>
{%endblock%}

hello_world/templates/hello_world/search_block.html
{% extends 'hello_world/index.html' %}
{% block content %}
<p>Following flights were found:</p>
    {%if result %}
        {%for flight in result %}
            {% for block in flight %}
            <p>Flight number: {{ block.FlightNumber }}</p>
            <p>Departure Airport: {{ block.DepartureAirport }}</p>
            <p>Arrival Airport: {{ block.ArrivalAirport }}</p>
            <p>Flight number: {{ block.FlightNumber }}</p><br><br>
            {% endfor %}
        {% endfor %}
    {%endif%}
    {%if form %}
        <p>Nothing was found</p>
    {%endif%}
{% endblock %}